const INTEL_CPU_DATA = {
  "generations": [
    {
      "id": "core2",
      "name": "Core 2 Duo/Quad 系列",
      "codeName": "Conroe / Penryn / Yorkfield",
      "years": "2006-2009",
      "architecture": "Core",
      "processNodes": ["65nm", "45nm"],
      "socket": "LGA 775",
      "highlights": "Intel 首款双核和四核桌面处理器，65nm(Conroe)到45nm(Penryn)过渡",
      "cpus": [
        {
                "model": "Core 2 Duo E6600",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.40 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2006",
                "l3Cache": "None (4 MB L2)",
                "memorySupport": "DDR2",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Duo E6700",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2006",
                "l3Cache": "None (4 MB L2)",
                "memorySupport": "DDR2",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Duo E8200",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (6 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Duo E8500",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.16 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (6 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Duo E8600",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.33 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q2 2008",
                "l3Cache": "None (6 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Extreme X6800",
                "brand": "Core 2",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.93 GHz",
                "boostClock": "N/A",
                "tdp": "75 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q3 2006",
                "l3Cache": "None (4 MB L2)",
                "memorySupport": "DDR2",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q8200",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.33 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2008",
                "l3Cache": "None (4 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q8400",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q2 2009",
                "l3Cache": "None (4 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q9300",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.50 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (6 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q9400",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2008",
                "l3Cache": "None (6 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q9450",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (12 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q9550",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.83 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (12 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Quad Q9650",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "N/A",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2008",
                "l3Cache": "None (12 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Extreme QX6700",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "N/A",
                "tdp": "130 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q4 2006",
                "l3Cache": "None (8 MB L2)",
                "memorySupport": "DDR2",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Extreme QX6800",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.93 GHz",
                "boostClock": "N/A",
                "tdp": "130 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q2 2007",
                "l3Cache": "None (8 MB L2)",
                "memorySupport": "DDR2",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Extreme QX6850",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "N/A",
                "tdp": "130 W",
                "process": "65 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q2 2007",
                "l3Cache": "None (8 MB L2)",
                "memorySupport": "DDR2 / DDR3 (1333 FSB)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core 2 Extreme QX9650",
                "brand": "Core 2",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "N/A",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 775",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q4 2007",
                "l3Cache": "None (12 MB L2)",
                "memorySupport": "DDR2 / DDR3",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen1",
      "name": "第1代 Core i 系列",
      "codeName": "Nehalem / Westmere",
      "years": "2008-2010",
      "architecture": "Nehalem",
      "processNodes": ["45nm", "32nm"],
      "socket": "LGA 1366 / LGA 1156",
      "highlights": "首次引入 Core i3/i5/i7 命名体系，集成内存控制器，支持超线程",
      "cpus": [
        {
                "model": "Core i7-930",
                "brand": "Core i7-930",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.80 GHz",
                "boostClock": "3.06 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2010",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-940",
                "brand": "Core i7-940",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.93 GHz",
                "boostClock": "3.20 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q4 2008",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-950",
                "brand": "Core i7-950",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.06 GHz",
                "boostClock": "3.33 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q2 2009",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-960",
                "brand": "Core i7-960",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "3.46 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q4 2009",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-965 Extreme",
                "brand": "Core i7-965",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "3.46 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q4 2008",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-975 Extreme",
                "brand": "Core i7-975",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.33 GHz",
                "boostClock": "3.60 GHz",
                "tdp": "130 W",
                "process": "45 nm",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q2 2009",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-980X Extreme",
                "brand": "Core i7-980X",
                "cores": 6,
                "threads": 12,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.33 GHz",
                "boostClock": "3.60 GHz",
                "tdp": "130 W",
                "process": "32 nm (Westmere)",
                "socket": "LGA 1366",
                "igpu": "None",
                "unlocked": true,
                "releaseDate": "Q1 2010",
                "l3Cache": "12 MB",
                "memorySupport": "DDR3 (Triple Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-870",
                "brand": "Core i7-870",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.93 GHz",
                "boostClock": "3.60 GHz",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 1156",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2009",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Dual Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-750",
                "brand": "Core i5-750",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.66 GHz",
                "boostClock": "3.20 GHz",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 1156",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2009",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Dual Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-760",
                "brand": "Core i5-760",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.80 GHz",
                "boostClock": "3.33 GHz",
                "tdp": "95 W",
                "process": "45 nm",
                "socket": "LGA 1156",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q3 2010",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3 (Dual Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-530",
                "brand": "Core i3-530",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.93 GHz",
                "boostClock": "N/A",
                "tdp": "73 W",
                "process": "32 nm (Clarkdale)",
                "socket": "LGA 1156",
                "igpu": "Intel HD Graphics (Ironlake)",
                "unlocked": false,
                "releaseDate": "Q1 2010",
                "l3Cache": "4 MB",
                "memorySupport": "DDR3 (Dual Channel)",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-540",
                "brand": "Core i3-540",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.06 GHz",
                "boostClock": "N/A",
                "tdp": "73 W",
                "process": "32 nm (Clarkdale)",
                "socket": "LGA 1156",
                "igpu": "Intel HD Graphics (Ironlake)",
                "unlocked": false,
                "releaseDate": "Q1 2010",
                "l3Cache": "4 MB",
                "memorySupport": "DDR3 (Dual Channel)",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen2",
      "name": "第2代 Core i 系列",
      "codeName": "Sandy Bridge",
      "years": "2011",
      "architecture": "Sandy Bridge",
      "processNodes": ["32nm"],
      "socket": "LGA 1155",
      "highlights": "首次在 CPU 内部集成 GPU（Ring Bus 架构），AVX 指令集",
      "cpus": [
        {
                "model": "Core i7-2700K",
                "brand": "Core i7-2700K",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "3.90 GHz",
                "tdp": "95 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 3000",
                "unlocked": true,
                "releaseDate": "Q4 2011",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3-1066/1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-2400",
                "brand": "Core i5-2400",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "3.40 GHz",
                "tdp": "95 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2000",
                "unlocked": false,
                "releaseDate": "Q1 2011",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1066/1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-2300",
                "brand": "Core i5-2300",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.80 GHz",
                "boostClock": "3.10 GHz",
                "tdp": "95 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2000",
                "unlocked": false,
                "releaseDate": "Q1 2011",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1066/1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-2120",
                "brand": "Core i3-2120",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.30 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2000",
                "unlocked": false,
                "releaseDate": "Q1 2011",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1066/1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-2105",
                "brand": "Core i3-2105",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 3000",
                "unlocked": false,
                "releaseDate": "Q2 2011",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1066/1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G620",
                "brand": "Pentium G620",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.60 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD (Sandy Bridge)",
                "unlocked": false,
                "releaseDate": "Q2 2011",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1066",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G840",
                "brand": "Pentium G840",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.80 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "32 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD (Sandy Bridge)",
                "unlocked": false,
                "releaseDate": "Q2 2011",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1066",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen3",
      "name": "第3代 Core i 系列",
      "codeName": "Ivy Bridge",
      "years": "2012",
      "architecture": "Ivy Bridge",
      "processNodes": ["22nm"],
      "socket": "LGA 1155",
      "highlights": "首款 22nm 三栅极晶体管工艺，功耗大幅降低，PCIe 3.0 支持",
      "cpus": [
        {
                "model": "Core i7-3770",
                "brand": "Core i7-3770",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.40 GHz",
                "boostClock": "3.90 GHz",
                "tdp": "77 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 4000",
                "unlocked": false,
                "releaseDate": "Q2 2012",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-3470",
                "brand": "Core i5-3470",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "3.60 GHz",
                "tdp": "77 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2500",
                "unlocked": false,
                "releaseDate": "Q2 2012",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-3450",
                "brand": "Core i5-3450",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "3.50 GHz",
                "tdp": "77 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2500",
                "unlocked": false,
                "releaseDate": "Q2 2012",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-3330",
                "brand": "Core i5-3330",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "3.20 GHz",
                "tdp": "77 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2500",
                "unlocked": false,
                "releaseDate": "Q3 2012",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-3220",
                "brand": "Core i3-3220",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.30 GHz",
                "boostClock": "N/A",
                "tdp": "55 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2500",
                "unlocked": false,
                "releaseDate": "Q3 2012",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-3240",
                "brand": "Core i3-3240",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.40 GHz",
                "boostClock": "N/A",
                "tdp": "55 W",
                "process": "22 nm",
                "socket": "LGA 1155",
                "igpu": "Intel HD 2500",
                "unlocked": false,
                "releaseDate": "Q3 2012",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen4",
      "name": "第4代 Core i 系列",
      "codeName": "Haswell",
      "years": "2013",
      "architecture": "Haswell",
      "processNodes": ["22nm"],
      "socket": "LGA 1150",
      "highlights": "引入 FIVR（全集成电压调节器），大幅改进核显，AVX2 指令集",
      "cpus": [
        {
                "model": "Core i7-4790K",
                "brand": "Core i7-4790K",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "4.00 GHz",
                "boostClock": "4.40 GHz",
                "tdp": "88 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": true,
                "releaseDate": "Q2 2014",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-4771",
                "brand": "Core i7-4771",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "3.90 GHz",
                "tdp": "84 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "8 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-4690K",
                "brand": "Core i5-4690K",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "3.90 GHz",
                "tdp": "88 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": true,
                "releaseDate": "Q2 2014",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-4590",
                "brand": "Core i5-4590",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.30 GHz",
                "boostClock": "3.70 GHz",
                "tdp": "84 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": false,
                "releaseDate": "Q2 2014",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-4460",
                "brand": "Core i5-4460",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "3.40 GHz",
                "tdp": "84 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": false,
                "releaseDate": "Q2 2014",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-4440",
                "brand": "Core i5-4440",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "3.30 GHz",
                "tdp": "84 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "6 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-4130",
                "brand": "Core i3-4130",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.40 GHz",
                "boostClock": "N/A",
                "tdp": "54 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4400",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-4330",
                "brand": "Core i3-4330",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "N/A",
                "tdp": "54 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD 4600",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333/1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G3220",
                "brand": "Pentium G3220",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "N/A",
                "tdp": "54 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD (Haswell)",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G3420",
                "brand": "Pentium G3420",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "N/A",
                "tdp": "54 W",
                "process": "22 nm",
                "socket": "LGA 1150",
                "igpu": "Intel HD (Haswell)",
                "unlocked": false,
                "releaseDate": "Q3 2013",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3-1333",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen5",
      "name": "第5代 Core i 系列",
      "codeName": "Broadwell",
      "years": "2014-2015",
      "architecture": "Broadwell",
      "processNodes": ["14nm"],
      "socket": "LGA 1150",
      "highlights": "首款 14nm 桌面处理器，Iris Pro 核显性能飞跃，桌面型号极少",
      "cpus": [
        {
                "model": "Core i7-5557U",
                "brand": "Core i7-5557U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "3.40 GHz",
                "tdp": "28 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel Iris 6100",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "4 MB",
                "memorySupport": "DDR3L-1866 / LPDDR3-1866",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-5500U",
                "brand": "Core i7-5500U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.40 GHz",
                "boostClock": "3.00 GHz",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 5500",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "4 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-5350U",
                "brand": "Core i5-5350U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "1.80 GHz",
                "boostClock": "2.90 GHz",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 6000",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-5300U",
                "brand": "Core i5-5300U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.30 GHz",
                "boostClock": "2.90 GHz",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 5500",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-5200U",
                "brand": "Core i5-5200U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.20 GHz",
                "boostClock": "2.70 GHz",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 5500",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-5010U",
                "brand": "Core i3-5010U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.10 GHz",
                "boostClock": "N/A",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 5500",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-5005U",
                "brand": "Core i3-5005U",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.00 GHz",
                "boostClock": "N/A",
                "tdp": "15 W",
                "process": "14 nm",
                "socket": "BGA 1168",
                "igpu": "Intel HD 5500",
                "unlocked": false,
                "releaseDate": "Q1 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR3L-1600",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen6",
      "name": "第6代 Core i 系列",
      "codeName": "Skylake",
      "years": "2015",
      "architecture": "Skylake",
      "processNodes": ["14nm"],
      "socket": "LGA 1151",
      "highlights": "支持 DDR4 内存，移除 FIVR，新插槽 LGA 1151",
      "cpus": [
        {
                "model": "Core i7-6700",
                "brand": "Core i7-6700",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.40 GHz",
                "boostClock": "4.00 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 530",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "8 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-6500",
                "brand": "Core i5-6500",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.20 GHz",
                "boostClock": "3.60 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 530",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-6400",
                "brand": "Core i5-6400",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.70 GHz",
                "boostClock": "3.30 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 530",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-6100",
                "brand": "Core i3-6100",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.70 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 530",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G4500",
                "brand": "Pentium G4500",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 530",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G4400",
                "brand": "Pentium G4400",
                "cores": 2,
                "threads": 2,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.30 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 510",
                "unlocked": false,
                "releaseDate": "Q3 2015",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2133 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G4560",
                "brand": "Pentium G4560",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.50 GHz",
                "boostClock": "N/A",
                "tdp": "54 W",
                "process": "14 nm (Kaby Lake)",
                "socket": "LGA 1151",
                "igpu": "Intel HD 610",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen7",
      "name": "第7代 Core i 系列",
      "codeName": "Kaby Lake",
      "years": "2016-2017",
      "architecture": "Kaby Lake",
      "processNodes": ["14nm+"],
      "socket": "LGA 1151",
      "highlights": "14nm+ 优化工艺，原生支持 4K 视频解码，Optane 内存支持",
      "cpus": [
        {
                "model": "Core i7-7700",
                "brand": "Core i7-7700",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "4.20 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "8 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-7500",
                "brand": "Core i5-7500",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.40 GHz",
                "boostClock": "3.80 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-7400",
                "brand": "Core i5-7400",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.00 GHz",
                "boostClock": "3.50 GHz",
                "tdp": "65 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-7100",
                "brand": "Core i3-7100",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.90 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-7300",
                "brand": "Core i3-7300",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "4.00 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "4 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        },
        {
                "model": "Pentium G4600",
                "brand": "Pentium G4600",
                "cores": 2,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "N/A",
                "tdp": "51 W",
                "process": "14 nm",
                "socket": "LGA 1151",
                "igpu": "Intel HD 630",
                "unlocked": false,
                "releaseDate": "Q1 2017",
                "l3Cache": "3 MB",
                "memorySupport": "DDR4-2400 / DDR3L-1600",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen8_9",
      "name": "第8/9代 Core i 系列",
      "codeName": "Coffee Lake / Coffee Lake Refresh",
      "years": "2017-2019",
      "architecture": "Coffee Lake",
      "processNodes": ["14nm++"],
      "socket": "LGA 1151 v2",
      "highlights": "核心数大幅增加，i7 升级为 6 核 12 线程，i9 首次登陆桌面平台",
      "cpus": [
        {
                "model": "Core i9-9900KS",
                "brand": "Core i9-9900KS",
                "cores": 8,
                "threads": 16,
                "pCores": null,
                "eCores": null,
                "baseClock": "4.00 GHz",
                "boostClock": "5.00 GHz",
                "tdp": "127 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q4 2019",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-9700K",
                "brand": "Core i7-9700K",
                "cores": 8,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "4.90 GHz",
                "tdp": "95 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q4 2018",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-8086K",
                "brand": "Core i7-8086K",
                "cores": 6,
                "threads": 12,
                "pCores": null,
                "eCores": null,
                "baseClock": "4.00 GHz",
                "boostClock": "5.00 GHz",
                "tdp": "95 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q2 2018",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-8600K",
                "brand": "Core i5-8600K",
                "cores": 6,
                "threads": 6,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "4.30 GHz",
                "tdp": "95 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q4 2017",
                "l3Cache": "9 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-9400F",
                "brand": "Core i5-9400F",
                "cores": 6,
                "threads": 6,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.90 GHz",
                "boostClock": "4.10 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q1 2019",
                "l3Cache": "9 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-8100",
                "brand": "Core i3-8100",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "N/A",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "Intel UHD 630",
                "unlocked": false,
                "releaseDate": "Q4 2017",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2400",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-9100F",
                "brand": "Core i3-9100F",
                "cores": 4,
                "threads": 4,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "4.20 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1151 (v2)",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q2 2019",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2400",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen10",
      "name": "第10代 Core i 系列",
      "codeName": "Comet Lake / Ice Lake",
      "years": "2019-2020",
      "architecture": "Comet Lake / Ice Lake",
      "processNodes": ["14nm+++", "10nm"],
      "socket": "LGA 1200",
      "highlights": "桌面端 i9 提升至 10 核 20 线程，新插槽 LGA 1200，笔记本端 10nm Ice Lake 首发",
      "cpus": [
        {
                "model": "Core i9-10850K",
                "brand": "Core i9-10850K",
                "cores": 10,
                "threads": 20,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "5.20 GHz",
                "tdp": "125 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q3 2020",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-2933",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i7-10700",
                "brand": "Core i7-10700",
                "cores": 8,
                "threads": 16,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.90 GHz",
                "boostClock": "4.80 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": false,
                "releaseDate": "Q2 2020",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-2933",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-10600K",
                "brand": "Core i5-10600K",
                "cores": 6,
                "threads": 12,
                "pCores": null,
                "eCores": null,
                "baseClock": "4.10 GHz",
                "boostClock": "4.80 GHz",
                "tdp": "125 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": true,
                "releaseDate": "Q2 2020",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-10500",
                "brand": "Core i5-10500",
                "cores": 6,
                "threads": 12,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.10 GHz",
                "boostClock": "4.50 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": false,
                "releaseDate": "Q2 2020",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i5-10400F",
                "brand": "Core i5-10400F",
                "cores": 6,
                "threads": 12,
                "pCores": null,
                "eCores": null,
                "baseClock": "2.90 GHz",
                "boostClock": "4.30 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "None",
                "unlocked": false,
                "releaseDate": "Q2 2020",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-10100",
                "brand": "Core i3-10100",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.60 GHz",
                "boostClock": "4.30 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": false,
                "releaseDate": "Q2 2020",
                "l3Cache": "6 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        },
        {
                "model": "Core i3-10300",
                "brand": "Core i3-10300",
                "cores": 4,
                "threads": 8,
                "pCores": null,
                "eCores": null,
                "baseClock": "3.70 GHz",
                "boostClock": "4.40 GHz",
                "tdp": "65 W",
                "process": "14 nm++",
                "socket": "LGA 1200",
                "igpu": "Intel UHD 630",
                "unlocked": false,
                "releaseDate": "Q2 2020",
                "l3Cache": "8 MB",
                "memorySupport": "DDR4-2666",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen11",
      "name": "第11代 Core i 系列",
      "codeName": "Rocket Lake",
      "years": "2021",
      "architecture": "Cypress Cove",
      "processNodes": ["14nm"],
      "socket": "LGA 1200",
      "highlights": "采用全新 Cypress Cove 架构，IPC 提升 19%，支持 PCIe 4.0，集成 UHD 750 核显",
      "cpus": [
        {
                "model": "i9-11900K",
                "brand": "i9-11900K",
                "cores": 8,
                "threads": 16,
                "pCores": 8,
                "eCores": 0,
                "baseClock": "3.5 GHz",
                "boostClock": "P-core: 5.3 GHz",
                "tdp": "125W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 750",
                "unlocked": true,
                "releaseDate": "2021年3月",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i9-11900",
                "brand": "i9-11900",
                "cores": 8,
                "threads": 16,
                "pCores": 8,
                "eCores": 0,
                "baseClock": "2.5 GHz",
                "boostClock": "P-core: 5.2 GHz",
                "tdp": "65W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 750",
                "unlocked": false,
                "releaseDate": "2021年3月",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-11700K",
                "brand": "i7-11700K",
                "cores": 8,
                "threads": 16,
                "pCores": 8,
                "eCores": 0,
                "baseClock": "3.6 GHz",
                "boostClock": "P-core: 5.0 GHz",
                "tdp": "125W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 750",
                "unlocked": true,
                "releaseDate": "2021年3月",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-11700",
                "brand": "i7-11700",
                "cores": 8,
                "threads": 16,
                "pCores": 8,
                "eCores": 0,
                "baseClock": "2.5 GHz",
                "boostClock": "P-core: 4.9 GHz",
                "tdp": "65W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 750",
                "unlocked": false,
                "releaseDate": "2021年3月",
                "l3Cache": "16 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-11600K",
                "brand": "i5-11600K",
                "cores": 6,
                "threads": 12,
                "pCores": 6,
                "eCores": 0,
                "baseClock": "3.9 GHz",
                "boostClock": "P-core: 4.9 GHz",
                "tdp": "125W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 750",
                "unlocked": true,
                "releaseDate": "2021年3月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-11400",
                "brand": "i5-11400",
                "cores": 6,
                "threads": 12,
                "pCores": 6,
                "eCores": 0,
                "baseClock": "2.6 GHz",
                "boostClock": "P-core: 4.4 GHz",
                "tdp": "65W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2021年3月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-11400F",
                "brand": "i5-11400F",
                "cores": 6,
                "threads": 12,
                "pCores": 6,
                "eCores": 0,
                "baseClock": "2.6 GHz",
                "boostClock": "P-core: 4.4 GHz",
                "tdp": "65W",
                "process": "14nm",
                "socket": "LGA 1200",
                "igpu": "无",
                "unlocked": false,
                "releaseDate": "2021年3月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen12",
      "name": "第12代 Core i 系列",
      "codeName": "Alder Lake",
      "years": "2021-2022",
      "architecture": "Alder Lake",
      "processNodes": ["Intel 7"],
      "socket": "LGA 1700",
      "highlights": "革命性混合架构，首次引入 P-core（性能核）+ E-core（能效核），支持 DDR5 和 PCIe 5.0",
      "cpus": [
        {
                "model": "i9-12900K",
                "brand": "i9-12900K",
                "cores": 16,
                "threads": 24,
                "pCores": 8,
                "eCores": 8,
                "baseClock": "3.2 GHz (P-core) / 2.4 GHz (E-core)",
                "boostClock": "P-core: 5.2 GHz / E-core: 3.9 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2021年11月",
                "l3Cache": "30 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i9-12900KS",
                "brand": "i9-12900KS",
                "cores": 16,
                "threads": 24,
                "pCores": 8,
                "eCores": 8,
                "baseClock": "3.4 GHz (P-core) / 2.5 GHz (E-core)",
                "boostClock": "P-core: 5.5 GHz / E-core: 4.0 GHz",
                "tdp": "150W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2022年4月",
                "l3Cache": "30 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-12700K",
                "brand": "i7-12700K",
                "cores": 12,
                "threads": 20,
                "pCores": 8,
                "eCores": 4,
                "baseClock": "3.6 GHz (P-core) / 2.7 GHz (E-core)",
                "boostClock": "P-core: 5.0 GHz / E-core: 3.8 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2021年11月",
                "l3Cache": "25 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-12700",
                "brand": "i7-12700",
                "cores": 12,
                "threads": 20,
                "pCores": 8,
                "eCores": 4,
                "baseClock": "2.1 GHz (P-core) / 1.6 GHz (E-core)",
                "boostClock": "P-core: 4.9 GHz / E-core: 3.6 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": false,
                "releaseDate": "2022年1月",
                "l3Cache": "25 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-12600K",
                "brand": "i5-12600K",
                "cores": 10,
                "threads": 16,
                "pCores": 6,
                "eCores": 4,
                "baseClock": "3.7 GHz (P-core) / 2.8 GHz (E-core)",
                "boostClock": "P-core: 4.9 GHz / E-core: 3.6 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2021年11月",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-12400",
                "brand": "i5-12400",
                "cores": 6,
                "threads": 12,
                "pCores": 6,
                "eCores": 0,
                "baseClock": "2.5 GHz",
                "boostClock": "P-core: 4.4 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2022年1月",
                "l3Cache": "18 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-12400F",
                "brand": "i5-12400F",
                "cores": 6,
                "threads": 12,
                "pCores": 6,
                "eCores": 0,
                "baseClock": "2.5 GHz",
                "boostClock": "P-core: 4.4 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "无",
                "unlocked": false,
                "releaseDate": "2022年1月",
                "l3Cache": "18 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i3-12100",
                "brand": "i3-12100",
                "cores": 4,
                "threads": 8,
                "pCores": 4,
                "eCores": 0,
                "baseClock": "3.3 GHz",
                "boostClock": "P-core: 4.3 GHz",
                "tdp": "60W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2022年1月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i3-12100F",
                "brand": "i3-12100F",
                "cores": 4,
                "threads": 8,
                "pCores": 4,
                "eCores": 0,
                "baseClock": "3.3 GHz",
                "boostClock": "P-core: 4.3 GHz",
                "tdp": "58W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "无",
                "unlocked": false,
                "releaseDate": "2022年1月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen13",
      "name": "第13代 Core i 系列",
      "codeName": "Raptor Lake",
      "years": "2022-2023",
      "architecture": "Raptor Lake",
      "processNodes": ["Intel 7(\u4f18\u5316)"],
      "socket": "LGA 1700",
      "highlights": "E-core 数量翻倍，缓存大幅增大，单核睿频突破 5.8GHz",
      "cpus": [
        {
                "model": "i9-13900K",
                "brand": "i9-13900K",
                "cores": 24,
                "threads": 32,
                "pCores": 8,
                "eCores": 16,
                "baseClock": "3.0 GHz (P-core) / 2.2 GHz (E-core)",
                "boostClock": "P-core: 5.8 GHz / E-core: 4.3 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2022年10月",
                "l3Cache": "36 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i9-13900KS",
                "brand": "i9-13900KS",
                "cores": 24,
                "threads": 32,
                "pCores": 8,
                "eCores": 16,
                "baseClock": "3.2 GHz (P-core) / 2.4 GHz (E-core)",
                "boostClock": "P-core: 6.0 GHz / E-core: 4.3 GHz",
                "tdp": "150W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2023年1月",
                "l3Cache": "36 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-13700K",
                "brand": "i7-13700K",
                "cores": 16,
                "threads": 24,
                "pCores": 8,
                "eCores": 8,
                "baseClock": "3.4 GHz (P-core) / 2.5 GHz (E-core)",
                "boostClock": "P-core: 5.4 GHz / E-core: 4.2 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2022年10月",
                "l3Cache": "30 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-13700",
                "brand": "i7-13700",
                "cores": 16,
                "threads": 24,
                "pCores": 8,
                "eCores": 8,
                "baseClock": "2.1 GHz (P-core) / 1.5 GHz (E-core)",
                "boostClock": "P-core: 5.2 GHz / E-core: 4.1 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": false,
                "releaseDate": "2023年1月",
                "l3Cache": "30 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-13600K",
                "brand": "i5-13600K",
                "cores": 14,
                "threads": 20,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "3.5 GHz (P-core) / 2.6 GHz (E-core)",
                "boostClock": "P-core: 5.1 GHz / E-core: 3.9 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2022年10月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-13500",
                "brand": "i5-13500",
                "cores": 14,
                "threads": 20,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "2.5 GHz (P-core) / 1.8 GHz (E-core)",
                "boostClock": "P-core: 4.8 GHz / E-core: 3.5 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": false,
                "releaseDate": "2023年1月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-13400",
                "brand": "i5-13400",
                "cores": 10,
                "threads": 16,
                "pCores": 6,
                "eCores": 4,
                "baseClock": "2.5 GHz (P-core) / 1.8 GHz (E-core)",
                "boostClock": "P-core: 4.6 GHz / E-core: 3.3 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2023年1月",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-13400F",
                "brand": "i5-13400F",
                "cores": 10,
                "threads": 16,
                "pCores": 6,
                "eCores": 4,
                "baseClock": "2.5 GHz (P-core) / 1.8 GHz (E-core)",
                "boostClock": "P-core: 4.6 GHz / E-core: 3.3 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "无",
                "unlocked": false,
                "releaseDate": "2023年1月",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i3-13100",
                "brand": "i3-13100",
                "cores": 4,
                "threads": 8,
                "pCores": 4,
                "eCores": 0,
                "baseClock": "3.4 GHz",
                "boostClock": "P-core: 4.5 GHz",
                "tdp": "60W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2023年1月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen14",
      "name": "第14代 Core i 系列",
      "codeName": "Raptor Lake Refresh",
      "years": "2023-2024",
      "architecture": "Raptor Lake Refresh",
      "processNodes": ["Intel 7"],
      "socket": "LGA 1700",
      "highlights": "Raptor Lake 小幅升级，频率提升，i7 增加 E-core，i9 单核睿频突破 6.0GHz",
      "cpus": [
        {
                "model": "i9-14900K",
                "brand": "i9-14900K",
                "cores": 24,
                "threads": 32,
                "pCores": 8,
                "eCores": 16,
                "baseClock": "3.2 GHz (P-core) / 2.4 GHz (E-core)",
                "boostClock": "P-core: 6.0 GHz / E-core: 4.4 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2023年10月",
                "l3Cache": "36 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i9-14900KS",
                "brand": "i9-14900KS",
                "cores": 24,
                "threads": 32,
                "pCores": 8,
                "eCores": 16,
                "baseClock": "3.2 GHz (P-core) / 2.4 GHz (E-core)",
                "boostClock": "P-core: 6.2 GHz / E-core: 4.5 GHz",
                "tdp": "150W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2024年3月",
                "l3Cache": "36 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-14700K",
                "brand": "i7-14700K",
                "cores": 20,
                "threads": 28,
                "pCores": 8,
                "eCores": 12,
                "baseClock": "3.4 GHz (P-core) / 2.5 GHz (E-core)",
                "boostClock": "P-core: 5.6 GHz / E-core: 4.3 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2023年10月",
                "l3Cache": "33 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i7-14700",
                "brand": "i7-14700",
                "cores": 20,
                "threads": 28,
                "pCores": 8,
                "eCores": 12,
                "baseClock": "2.1 GHz (P-core) / 1.5 GHz (E-core)",
                "boostClock": "P-core: 5.4 GHz / E-core: 4.2 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": false,
                "releaseDate": "2024年1月",
                "l3Cache": "33 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-14600K",
                "brand": "i5-14600K",
                "cores": 14,
                "threads": 20,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "3.5 GHz (P-core) / 2.6 GHz (E-core)",
                "boostClock": "P-core: 5.3 GHz / E-core: 4.0 GHz",
                "tdp": "125W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 770",
                "unlocked": true,
                "releaseDate": "2023年10月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR4-3200 / DDR5-5600",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-14400",
                "brand": "i5-14400",
                "cores": 10,
                "threads": 16,
                "pCores": 6,
                "eCores": 4,
                "baseClock": "2.5 GHz (P-core) / 1.8 GHz (E-core)",
                "boostClock": "P-core: 4.7 GHz / E-core: 3.5 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2024年1月",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i5-14400F",
                "brand": "i5-14400F",
                "cores": 10,
                "threads": 16,
                "pCores": 6,
                "eCores": 4,
                "baseClock": "2.5 GHz (P-core) / 1.8 GHz (E-core)",
                "boostClock": "P-core: 4.7 GHz / E-core: 3.5 GHz",
                "tdp": "65W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "无",
                "unlocked": false,
                "releaseDate": "2024年1月",
                "l3Cache": "20 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        },
        {
                "model": "i3-14100",
                "brand": "i3-14100",
                "cores": 4,
                "threads": 8,
                "pCores": 4,
                "eCores": 0,
                "baseClock": "3.5 GHz",
                "boostClock": "P-core: 4.7 GHz",
                "tdp": "60W",
                "process": "Intel 7 (10nm ESF)",
                "socket": "LGA 1700",
                "igpu": "Intel UHD Graphics 730",
                "unlocked": false,
                "releaseDate": "2024年1月",
                "l3Cache": "12 MB",
                "memorySupport": "DDR4-3200 / DDR5-4800",
                "maxMemory": "N/A"
        }
]
    },
    {
      "id": "gen_ultra",
      "name": "Core Ultra 系列",
      "codeName": "Meteor Lake / Arrow Lake / Lunar Lake",
      "years": "2023-2025",
      "architecture": "Meteor Lake / Arrow Lake",
      "processNodes": ["Intel 4 + TSMC N5/N6"],
      "socket": "LGA 1851 / BGA",
      "highlights": "全新 Core Ultra 命名体系取代 Core i，集成 NPU，Foveros 3D 封装，Arc 核显",
      "cpus": [
        {
                "model": "Ultra 9 285K (Arrow Lake)",
                "brand": "Ultra 9",
                "cores": 24,
                "threads": 24,
                "pCores": 8,
                "eCores": 16,
                "baseClock": "3.7 GHz (P-core) / 3.2 GHz (E-core)",
                "boostClock": "P-core: 5.7 GHz / E-core: 4.6 GHz",
                "tdp": "125W",
                "process": "TSMC N3B (Compute Tile)",
                "socket": "LGA 1851",
                "igpu": "Intel Arc Graphics (4 Xe-cores)",
                "unlocked": true,
                "releaseDate": "2024年10月",
                "l3Cache": "36 MB",
                "memorySupport": "DDR5-6400 / DDR5-8000 (OC)",
                "maxMemory": "N/A"
        },
        {
                "model": "Ultra 7 265K (Arrow Lake)",
                "brand": "Ultra 7",
                "cores": 20,
                "threads": 20,
                "pCores": 8,
                "eCores": 12,
                "baseClock": "3.9 GHz (P-core) / 3.3 GHz (E-core)",
                "boostClock": "P-core: 5.5 GHz / E-core: 4.6 GHz",
                "tdp": "125W",
                "process": "TSMC N3B (Compute Tile)",
                "socket": "LGA 1851",
                "igpu": "Intel Arc Graphics (4 Xe-cores)",
                "unlocked": true,
                "releaseDate": "2024年10月",
                "l3Cache": "30 MB",
                "memorySupport": "DDR5-6400 / DDR5-8000 (OC)",
                "maxMemory": "N/A"
        },
        {
                "model": "Ultra 5 245K (Arrow Lake)",
                "brand": "Ultra 5",
                "cores": 14,
                "threads": 14,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "4.2 GHz (P-core) / 3.6 GHz (E-core)",
                "boostClock": "P-core: 5.2 GHz / E-core: 4.6 GHz",
                "tdp": "125W",
                "process": "TSMC N3B (Compute Tile)",
                "socket": "LGA 1851",
                "igpu": "Intel Arc Graphics (4 Xe-cores)",
                "unlocked": true,
                "releaseDate": "2024年10月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR5-6400 / DDR5-8000 (OC)",
                "maxMemory": "N/A"
        },
        {
                "model": "Ultra 9 185H (Meteor Lake)",
                "brand": "Ultra 9",
                "cores": 16,
                "threads": 22,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "2.3 GHz (P-core) / 1.8 GHz (E-core) / 1.0 GHz (LP E-core)",
                "boostClock": "P-core: 5.1 GHz / E-core: 3.8 GHz / LP E-core: 2.5 GHz",
                "tdp": "45W",
                "process": "Intel 4 (Compute Tile)",
                "socket": "BGA 2049 (笔记本)",
                "igpu": "Intel Arc Graphics (8 Xe-cores)",
                "unlocked": false,
                "releaseDate": "2023年12月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR5-5600 / LPDDR5x-7467",
                "maxMemory": "N/A"
        },
        {
                "model": "Ultra 7 155H (Meteor Lake)",
                "brand": "Ultra 7",
                "cores": 16,
                "threads": 22,
                "pCores": 6,
                "eCores": 8,
                "baseClock": "2.1 GHz (P-core) / 1.6 GHz (E-core) / 1.0 GHz (LP E-core)",
                "boostClock": "P-core: 4.8 GHz / E-core: 3.8 GHz / LP E-core: 2.5 GHz",
                "tdp": "28W",
                "process": "Intel 4 (Compute Tile)",
                "socket": "BGA 2049 (笔记本)",
                "igpu": "Intel Arc Graphics (8 Xe-cores)",
                "unlocked": false,
                "releaseDate": "2023年12月",
                "l3Cache": "24 MB",
                "memorySupport": "DDR5-5600 / LPDDR5x-7467",
                "maxMemory": "N/A"
        },
        {
                "model": "Ultra 5 125H (Meteor Lake)",
                "brand": "Ultra 5",
                "cores": 14,
                "threads": 18,
                "pCores": 4,
                "eCores": 8,
                "baseClock": "2.4 GHz (P-core) / 1.8 GHz (E-core) / 1.0 GHz (LP E-core)",
                "boostClock": "P-core: 4.5 GHz / E-core: 3.6 GHz / LP E-core: 2.5 GHz",
                "tdp": "28W",
                "process": "Intel 4 (Compute Tile)",
                "socket": "BGA 2049 (笔记本)",
                "igpu": "Intel Arc Graphics (7 Xe-cores)",
                "unlocked": false,
                "releaseDate": "2023年12月",
                "l3Cache": "18 MB",
                "memorySupport": "DDR5-5600 / LPDDR5x-7467",
                "maxMemory": "N/A"
        }
]
    }

  ]
};